version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
          - "@smithy/*"
      aws-cdk:
        patterns:
          - "aws-cdk-lib"
          - "cdk-nag"
          - "constructs"
      powertools:
        patterns:
          - "@aws-lambda-powertools/*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      testing:
        patterns:
          - "jest"
          - "ts-jest"
          - "@types/jest"
          - "aws-sdk-client-mock*"
      types:
        patterns:
          - "@types/*"
        exclude-patterns:
          - "@types/jest"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
